"""Research methodology, verification rules, and output format templates."""

RESEARCH_METHODOLOGY = (
    "## Research Methodology\n\n"
    "Follow this process to investigate the topic:\n\n"
    "1. **Parse the topic.** Identify key concepts and any seed URLs in the prompt.\n"
    "2. **Read seed URLs first.** If the user provided URLs, fetch and read them "
    "with `WebFetch` before searching. These are your primary sources.\n"
    "3. **Search for primary sources.** Use `WebSearch` to find official documentation, "
    "academic papers, GitHub repositories, and API references. Fetch and read each.\n"
    "4. **Search for secondary sources.** Use `WebSearch` to find tutorials, forum "
    "discussions (Reddit, StackOverflow, HuggingFace, Discord archives), blog posts, "
    "and video descriptions. Fetch and read each.\n"
    "5. **Follow reference chains.** Papers cite other papers. Repos link to docs. "
    "Docs link to APIs. Follow these links to build complete understanding.\n"
    "6. **Extract and verify.** For each source: extract key information, note code "
    "examples with their context, record parameter recommendations. Cross-reference "
    "every factual claim across 2+ sources before including it.\n"
    "7. **Identify actionable knowledge.** Focus on: recommended settings, parameters, "
    "configurations, samplers, schedulers. Best practices. Common pitfalls. "
    "Working code examples.\n"
    "8. **Tag confidence.** Assign a confidence level to each claim per the "
    "verification rules below.\n"
    "9. **Write the output.** Synthesize findings into the output file using the "
    "format template below. Write the file using the Write tool."
)


VERIFICATION_RULES = (
    "## Verification Rules\n\n"
    "Every claim in the report must meet a confidence threshold:\n\n"
    "- **High confidence** — Verified by 2+ independent sources (e.g. official docs + "
    "repo code, paper + implementation). Include without qualification.\n"
    "- **Medium confidence** — From a single authoritative source (official docs, paper) "
    "or consistent across 2+ non-authoritative sources (forums, tutorials). Include with "
    "attribution: *Based on [source]*.\n"
    "- **Low confidence** — Single non-authoritative source, or conflicting information "
    "across sources. Include only if highly relevant, clearly marked: "
    "*Unverified — [source] suggests...*\n"
    "- **Omit** — Claims that contradict authoritative sources or cannot be sourced. "
    "Do not include.\n\n"
    "Code examples must be verified against official documentation or a working "
    "repository. Never fabricate code examples from inference alone. If adapting "
    "an example, cite the original source."
)


SKILL_FORMAT = (
    "## Output Format: SKILL.md\n\n"
    "Write a SKILL.md file with YAML frontmatter and structured knowledge sections.\n\n"
    "```\n"
    "---\n"
    "name: <topic-slug>\n"
    "description: <one-line description of what this skill provides knowledge about>\n"
    "---\n"
    "\n"
    "## Overview\n"
    "<what this technology/tool/concept is and why it matters>\n"
    "\n"
    "## Key Concepts\n"
    "<core concepts needed to understand and use it effectively>\n"
    "\n"
    "## Setup / Installation\n"
    "<how to install, configure, and get started — with exact commands>\n"
    "\n"
    "## Usage\n"
    "<how to use it, with working code examples for common tasks>\n"
    "\n"
    "## Configuration & Parameters\n"
    "<recommended settings, parameters, samplers, schedulers — whatever is "
    "configurable. Include defaults, recommended values, and what each controls>\n"
    "\n"
    "## Best Practices\n"
    "<proven approaches, performance tips, quality recommendations>\n"
    "\n"
    "## Common Pitfalls\n"
    "<mistakes people make, error messages and fixes, troubleshooting steps>\n"
    "\n"
    "## Confidence Notes\n"
    "<any medium or low confidence items collected here with reasoning>\n"
    "\n"
    "## Sources\n"
    "<all URLs consulted, grouped as Primary and Secondary>\n"
    "```\n\n"
    "Keep the content dense and actionable. Prefer code examples over prose. "
    "Every recommendation should be specific enough to act on."
)


REPORT_FORMAT = (
    "## Output Format: Markdown Report\n\n"
    "Write a detailed markdown report with the following structure:\n\n"
    "```\n"
    "# Research Report: <topic>\n"
    "\n"
    "**Generated:** <current date>\n"
    "**Sources consulted:** <count>\n"
    "\n"
    "## Executive Summary\n"
    "<3-5 sentence overview of key findings>\n"
    "\n"
    "## Background\n"
    "<context, history, what problem this solves>\n"
    "\n"
    "## Key Findings\n"
    "<main discoveries organized by sub-topic>\n"
    "\n"
    "## Code Examples\n"
    "<working, verified code examples with explanations>\n"
    "\n"
    "## Configuration & Parameters\n"
    "<detailed parameter/setting recommendations with rationale>\n"
    "\n"
    "## Best Practices\n"
    "<proven approaches from the community and official sources>\n"
    "\n"
    "## Common Pitfalls\n"
    "<documented issues, their causes, and solutions>\n"
    "\n"
    "## Confidence Notes\n"
    "<any medium or low confidence items with reasoning and source attribution>\n"
    "\n"
    "## Sources\n"
    "### Primary\n"
    "<official docs, papers, repos — with URLs>\n"
    "### Secondary\n"
    "<tutorials, forums, blog posts — with URLs>\n"
    "```\n\n"
    "Be thorough and detailed. Include all relevant information found. "
    "Every recommendation should cite its source."
)
